scrape_configs:
  - job_name: 'MyAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['gitchat-bridge:8080']
#        Descomentar para apontar para o spring boot rodando localmente e não em conteiner
#     - targets: [''172.17.0.1:8080']
        labels:
          application: 'My Spring Boot Application'
  - job_name: 'docker'
    static_configs:
      - targets: ['172.17.0.1:9323']
